# Basics of `ggplot`

(Refer heavily to https://ggplot2-book.org/introduction.html)

#### Learning goals {-}

- Understand what `ggplot2` is and why it's used
- Be able to think conceptually in the framework of the "grammar of graphics"
- Learn the syntax for creating different plots using using `ggplot2`

## Thinking about data visualization

Let's start with a video: https://youtu.be/5Zg-C8AAIGg.

And one by Hans Rosling too: https://www.youtube.com/watch?v=FACK2knC08E

## What is `ggplot`?  {-}

`ggplot2` is an R package. It's one of the most downloaded packages in the R universe, and has become the gold standard for data visualization. It's extremely powerful and flexible, and allows for creating lots of visualizations of different types, ranging from maps to bare-bones academic publications, to complex, paneled charts with labeling, etc. Because the syntax is so different from "base" R, it can give the impression of having a somewhat steep learning curve. But in reality, because the principles are so conceptually simple, learning is fairly fast. Generally those who choose to learn it stick with it; that is, once you go gg, you don't go back.

## The name and concept  {-}

"GG" stands for "grammar of graphics", with "grammar" meaning "the fundamental principles or rules of an art or science" [@layered-grammar]. The most well-known "grammar of graphics" was written in 2005 and laid out some abstract principles for describing statistical graphics [@10.5555/1088896]. The basic idea is that all graphs can be described using a _layered_ grammar, and that all graphs have the same general elements...

- data
- geometric objects
- aesthetics (mapping) of variables to objects

... whereas some graphs have additional elements...

- statistical transformations
- scales
- facets

## Practice {-}

Before getting to examples, hands-on together practice.

DEPRECATED BELOW THIS LINE


## A practical example {-}

Let's get practical (we'll get back to the theory later). 

First, let's read in some data on health from the World Bank:

```{r}
library(readr)
health <- read_csv('https://github.com/ZeningQu/World-Bank-Data-by-Indicators/raw/master/health/health.csv')
```

Canvas
Canvas + variables (mapping)
Canvas + variables (mapping) + geometric objects

## Learning examples {-}

### Perfecting the canvas {-}

Adjust y / x limits

Add a different background

Change x / y labels

### Aesthetic attributes of the geoms {-}


A scatterplot


Add a line of best fit



Add title / subtitle / caption

#### Review assignment  {-}

_Note: Under construction!_

## Other resources  {-}

_Note: Under construction!_


