# `R Markdown` {-}

`R Markdown` is the combination of `R` and `Markdown`. It is a tool in the toolbox of "literate programming" and allows you to weave computer-speak (code) and human-speak (English, or any other language) into one combined document.


### In-class activity {-}

Let's not talk about it. Let's just do it.

#### Starting the file {-}

- Create a repository on github called `report`.  
- Clone that repository to your local machine.  
- `cd` into that repository.  
- Open Rstudio.  
- Click File -> New File -> R Markdown  
- Fill out "Title", "Author", and click "Set to HTML"  
- Type  ctrl + s to save your file in the recently cloned `report` repository  

#### Compiling your report {-}

- Have a look at the document. What does each section mean?  
- Click the "knit" button at the top.  
- Cool, right? But also kind of boring. Let's make some changes to this report.  

#### Modifying the template {-}

- First, let's replace the "setup chunk" with the below.  

```{r, include=FALSE, echo = TRUE, eval = TRUE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = TRUE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE)
```

- Then, let's change the title to some interesting question.  
- Now, let's delete all of the other stuff in the template so far (beginning at "R Markdown").  
- Let's put in some headers, using the hashtag symbol. We'll make the following sections: `Introduction`, `Methods`, `Results`, `Conclusion`.  
- Let's put in some text too.  
- Let's knit, to make sure that we did not break anything.  Good? Great.  


#### Formatting {-}

- Headers  
- In-line code-formatting  
- In-line code processing  
- Italitcs  
- Bold  
- Echo  
- Eval  

#### Bibliography management {-}

- From the command line, create a new file: `touch bibliography.bib`.  
- Look up https://www.researchgate.net/publication/260642613_Statistical_exponential_formulas_for_homogeneous_diffusion  
- Get the DOI  
- Go to https://doi2bib.org/  
- Get the bibtex format  
- Copy-paste into your bib file  
- Write some line about a paper  
- Cite that line using citation notation  
- Add `bibliography: bibliography.bib` to your yaml


#### Wrapping up {-}


- Push your code to github.  




#### Exercises {-}

Before getting started, think of a testable hypothesis which can be answered via a survey of your friends and classmates. For example: "woman have more dreams than men" or "people born abroad have shorter last names than people born in the USA" or "shoe size is associated with GPA".  

1. Create a new R markdown document. Name it `paper.Rmd`. Make it in the same repo as your previous RMarkdown document.

2. Replace the setup chunk with the one used in the in-class exercise (above)

3. Create a google form survey with at least 5 interesting questions on a topic which interests you (one topic, five questions).

4. Get at least 5 people to fill out your survey. 

5. In your survey results, create a google spreadsheet.  

6. In the sharing settings of your google spreadsheet, set to "public".  

7. Copy the URL of your survey results.  

8. Create an R chunk in your `paper.Rmd`.  

9. Use the `gsheet` package to read your survey results as a dataframe.

10. After reading in the data, create the following sections in your report: `Introduction`, `Methods`, `Results`, `Conclusion`. 

11. Spend 5-15 minutes on the internet reading about your topic / hypotheses. 

12. Find 2-5 authors/articles of interest related to your topic. Cite them in the introduction.

13. Describe in plain English your approach to testing your hypothesis in the "Methods" section.

14. After the "Methods" section, write the R code (in an `echo`ed chunk) which tests your hypothesis.

15. In the "Results" section, write a description of both (a) your sample and (b) your results. Include at least two charts. Include at least one table.

16. In the "Conclusion" section, write interesting reflection on your data.

17. Got here? Cool, you're fast. Now configure your computer to generate pdfs via Rmarkdown: [mac](https://medium.com/@sorenlind/create-pdf-reports-using-r-r-markdown-latex-and-knitr-on-macos-high-sierra-e7b5705c9fd) / [windows](https://medium.com/@sorenlind/create-pdf-reports-using-r-r-markdown-latex-and-knitr-on-windows-10-952b0c48bfa9)

18. Make your paper in pdf.  

19. Check out https://www.datadreaming.org/post/r-markdown-theme-gallery/

20. Publish your paper to the internet

21. Push your code to git

22. Check out how to make presentations in Rmarkdown: https://rmarkdown.rstudio.com/lesson-11.html. Make one.  

23. Check out how to make dashboards in Rmarkdown: https://rmarkdown.rstudio.com/lesson-12.html. Make one.

24. Change your citation style. Use a new csl from https://github.com/citation-style-language/styles

