# Sewanee's climate

#### Learning goals {-}

* This is a review exercise: apply the `dplyr` and `ggplot` skills introduced in the previous modules and the `Deep R` modules on *Working with Dates and Times* and *Working with Text* to analyze climate records for Sewanee, TN, USA.    

&nbsp;  

```{r,echo=TRUE,collapse=TRUE, eval = FALSE}
library(weatherr)
library(tidygeocoder)
sewanee_location <- geo(address = '735 University Avenue, Sewanee TN')
fc <- locationforecast(lon = sewanee_location$long,
                       lat = sewanee_location$lat)

```

**1.** Plot the forecasted temperature

**2.** Get average cloudiness by day.

**3.** Plot average cloudiness by day.

**4.** Plot humidity.

**5.** Get the maximum temperature by hour (without date). Plot it.

**6.** Make a variable called `date`. This should just be the date (without the time)

**7.** Plot wind direction over time, with the line color showing the date.

**8.** Create a variable called `perfect`. This should include conditions indicating whether the weather in that moment is perfect.

**9.** How much of the next few days is going to be perfect?

**10.** Create a variable called `hour`. What is the best time of day (across all days) to fly a kite in the next few days?

**11.** Use `date` to get the average windspeed per day. What is the best day to fly a kite this week?

**12.** Get the average temperature by `hour`. What is, on average, the coldest moment of the day? And the hottest?



