# Elements of structure & style {#style}


## Structuring your writing {-}

### Paragraph structure {-}

Each paragraph should have a sentence that clearly encapsulates the paragraph’s main point. This usually comes at either the beginning or end of the paragraph.


### Sentence-level structure {-}

In a strong argument, sentences are connected in a chain. 

**Not good:** "A is something interesting. B is something interesting. C is ..."  

**Good:** "A is related to B. B is related to C. C is related D..."  


## Writing style {-}


### Sharp & precise writing {-}


### Use of passive voice and first-person {-}

First-person is OK (“To address this knowledge gap, I…”), but ...  

(1) avoid self-aware commentary (“In this part of the Introduction, I will..”, “No Introduction would be complete without …”), and  

(2) avoid self-centered commentary on how difficult something was ("In this complicated analysis, I was able to ..."). *Always* avoid "I was able to..." statements.  


### Writing about results {-}


### Citing references {-}


### Referencing tables & figures {-}


### Formatting *Literature Cited* {-}  


## Formatting tables {-}


## Formatting figures {-}  


### Plots {-}


### Maps {-}


### Diagrams {-}  


