# Presentations

Just as good writing in science is no different from good writing anywhere else, good research talks should be a good talk by any standard. The only difference should be the *target audience.*  Far too often, data scientists are given a pass for poor presentations and boring delivery. We believe that should change.  

Research talks are typically given to colleagues who share some level of familiarity with your study topic; but those colleagues are still humans and they deserve to listen to an enjoyable talk that allows them to connect to the speaker.  

As a data scientist, you will have to be adept at preparing two types of presentations: (1) talks for colleagues and (2) talks for the public.  

Below we first provide standards that should apply to *any* talk for *any* audience. Second, we specify which additional standards to consider, depending on your audience. 

### Standards for all presentations {-}   

#### Content & substance {-}

##### First moments {-}  
- The first seconds of your talk are an excellent, engaging, and relevant attention getter,  
- the tone of which matches and sets the stage for the remainder of the talk.  

##### Early audience orientation {-}  
- Sound orientation to topic and clear thesis delivered early in talk.   
- Introductory moments includes preview of main points.   
- Credibility is firmly established, but only after the audience is invested in the topic.   

##### Research & evidence {-}  
- Reason & evidence are used as part of case being made. 
- Facts, numbers, and statistics are used effectively.  
- Includes only the absolutely essential details regarding research sources, methods, and analyses.  
- Evidence is not oversold as truth. The uncertainty and ignorance inherent to science is not ignored.  

##### Story & narrative {-}  
- The organization of the talk takes the form of a story, taking the audience on a shared journey.  
- Within this framework, anecdotes and stories are used as a medium for connecting the
audience to facts, evidence, and emotional components of your case.    

##### Relevance & Importance {-}  
- A compelling case for the importance of the topic to the audience’s lives and/or their shared interests.    
- The connection between the audience’s shared interests and the topic is pointed to clearly and consistently.  

##### Pre- & Misconceptions {-} 
- Content & delivery demonstrate anticipation of preconceptions regarding the topic and the presenter.   
- Content demonstrates understanding of common misconceptions regarding the topic.  
- These pre- and misconceptions are addressed and moved beyond deftly and thoroughly.  
- No elephants in the room go unmentioned.  

##### Final moments {-}
- Provides a clear and memorable summary of points and refers back to thesis/big picture.  
- Ends with strong call to action, or at least a vision for next steps, solidly grounded in data presented.

##### Organization overall {-}
- Organization of the content amounts to a strategic and persuasive case, in which rational, emotional,
and narrative components are woven together with deliberate care.  
- This organization is made clear to the audience: throughout the talk, the audience is given transitions
and signposts and reminders that allow them to readily reconstruct the case being made.  
- The communication of this order is obvious without being condescending or ineffectually repetitive.  
- The talk is delivered within the allocated time window, reflecting appropriate organization and respect for others' time.  


#### Delivery & style {-}

##### Preparation {-} 
- The speaker is clearly well-prepared, and this is evident in the timing of the talk, familiarity with
visual aids and what will be said next, and little to no reliance upon notes.  

##### Speech {-} 
- Vocal expression (projection and volume) is natural and authentic;  
- Excellent use of variation in vocal intensity, tone, and expression.  
- Pace of speech is always easy to follow.  
- Tone is conversational and sincere.  
- Each thought is brought to completion without trailing off or rambling.  
- Lack of vocal fillers (e.g., ummm, so…..).  
- Impactful use of pauses and silence.  

##### Language {-} 
- Speaker is able to articulate what she means clearly through eloquent word choice and
premeditated sentences.  
- Language level is considerate of audience’s current knowledge, particularly in science.  
- Jargon, abbreviations, and acronyms are avoided; any that must be used is explained.  
- Comparisons and analogies are used effectively without further complicating a concept.  

##### Explanation {-} 
- Any word that may not be universally understood is explained, either explicitly or within
abundant context.  
- Any concept that may not be universally understood is explained carefully.  
- These explanations occur at a level appropriate to audience.  

##### Non-verbal delivery: The “Second Conversation” {-}  
- Attire & composure reflects the utmost sincerity and professionalism, without sacrificing
authenticity.  
- The speaker is expressive and compelling through eye contact and facial expressions.  
- Body language (posture, gestures, and movements) exude poise and earnest engagement.  
- Body language effectively augments the spoken word, in both timing and affect.  
- Eyes, movements and gestures are not distracting and do not disclose anxiety or discomfort.  

##### Mistakes {-}  
- Any mistakes are handled in a graceful and self-forgiving manner, and recovery is quick.  
- The speaker demonstrates resilience and endurance; multiple mistakes do not lead to a decline
in composure or energy level.  

##### Attentive, responsive, & adaptive {-}
- The speaker actively maintains audience attention throughout, rather than just assuming
attention is there or not responding accordingly if it clearly isn’t.  
- The speaker establishes an active dialogue between themselves and the audience, either directly
(through responses or questions), or indirectly (through sharing moments of laughter, joy, pain,
anger, disgust, etc.).  
- Speaker reiterates, clarifies, and changes course adaptively in response to their read of the
audience.  
- Speaker knowledgeably and concisely answers appropriate questions, if any.  
- Evidence that the speaker researched and anticipated common questions, as appropriate.  


#### Rapport & Relating  {-}

##### Energetic & credible {-}
- Professional but enjoyable  
- Enthusiastic but genuine and believable  
- Excited but not overbearing  

##### Human & relatable {-}  
- Poise without intimidation  
- Confidence without arrogance  
- Comfort & ease without apathy or indifference  
- Vulnerability without fragility or volatility  

##### Inclusive & welcoming {-}
- When appropriate, uses inclusive language (“we” and “our” instead of “I” and “my”; non-gendered
pronouns, politically tolerant language, etc.)  
- Creates common ground by strongly emphasizing common goals, values and/or experiences.  

#### Visual aids {-}

##### Strategic use {-} 
- Visual aids complement the spoken word. Redundancy (if any) between what is spoken and what is
displayed is strategic, not used as a crutch for presenting.  
- Visual aids are not *over-used*, and do not obstruct the audience’s ability to listen to and follow the
narrative thread of the talk.  
- Visual aids are not *under-used* if spoken concepts are too complicated. For instance, if a list of
numbers absolutely must be shared, it is best to provide them visually in addition to saying them.  

##### Design & display {-} 
- Visual aids are of professional quality, not sloppy or thrown together.  
- Visual aids prioritize simplicity, clarity, and good principles of design.  
- Color palettes are sensitive to color-blind audiences.  

##### Visualizing information {-}
- Use of text is minimized.  
- Text is an appropriate size and font.  
- Complicated figures are avoided.  
- Any data visualization has been reduced to the simplest possible form.  


### Talking to the public {-}  

When speaking as a researcher to the public, some of these standards need to be prioritized above others. The public is a much more diverse audience than your colleagues are. They do not necessarily know you, nor do they necessarily trust you or agree with you.  To help them engage with you successfully and actually listen to what you have to say, we recommend the following adjustments: 

- A public-facing talk must have **a clear and simple message** -- a *single* idea worth spreading.  

- To convince the public of that idea, you must **dial down the research and replace it with stories, emotion, and empathy.**  Your case needs to rely heavily upon appeals to the heart and gut of the audience.  By end of talk, you want the audience to be emotionally invested in seeing the call to action come to fruition.   

- That said, make sure that those **emotional appeals are made with nuance and discretion**, without exploiting victims or the voiceless. Do not be condescending toward your audience or anyone unlikely to be in your audience. 

**- Minimize the number of facts, numbers, and statistics.** If you *must* use them, *never* use them in isolation from the emotional aspects of your talk. Do not simply hurl facts at your audience. Within an empathic storytelling framework, anecdotes and stories are used as the primary medium for connecting the audience to facts, evidence, and emotional components of your case. Don't shy away from your data, but use it very carefully. Ultimately, the talk is a persuasive case for elevating the importance of research in our lives.  

**- End with strong call to action**,  solidly grounded in the data and stories you have presented. Make sure that call to action is related to your talk in obvious and intuitive ways. Make sure it is a meaningful action by which audience members are actually able to make a difference. Finally, make sure that this call to action is expressed succinctly and memorably, as an effective and simple slogan. 

  
  
This is a [pretty good example](https://www.youtube.com/watch?v=mae2eugjUsU) of a scientifically oriented talk to the public:  




