---
output: 
  html_document:
    includes:
      in_header: header.html
---

# Template

## Learning goals {-}

* Item 1  
* Item 2  
* Item 3  

## Tutorial video {-}

<iframe src="https://player.vimeo.com/video/152709121?title=0&byline=0&portrait=0" width="640" height="360" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
<p><a href="https://vimeo.com/152709121">Bangarang - Crew Briefing</a> from <a href="https://vimeo.com/lukepadgett">Luke Padgett</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

## Basics  {-}

```{r}

```

### Exercise 1 {-}

<!---LEARNR EX 1-->

<iframe style="margin:0 auto; min-width: 100%;" id="myIframe1" class="interactive" src="https://ericmkeen.shinyapps.io/learnr_app1/" scrolling="yes" frameborder="no"></iframe>

<!---------------->


## Review assignment {-}

Introduce data

```{r}
# Read in data from "./data/" subdirectory

```

Introduce task(s)


```{r}
# Read in data from "./data/" subdirectory

```

## Other Resources

https://desiree.rbind.io/post/2020/learnr-iframes/

https://rstudio.github.io/learnr/


<script>
  iFrameResize({}, ".interactive");
</script>
